name: bnotes
description: Note taking application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+17

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  adaptive_breakpoints: ^0.1.1
  bitsdojo_window: ^0.1.5
  cupertino_icons: ^1.0.4
  flutter_markdown: ^0.6.14
  flutter_svg: ^1.1.6
  http: ^0.13.6
  iconsax: ^0.0.8
  intl: ^0.18.0
  shared_preferences: ^2.0.13
  sqflite: ^2.2.8+4
  uuid: ^3.0.5
  url_launcher: ^6.0.20
  universal_platform: ^1.0.0+1
  path: ^1.8.3
  yaru_icons: ^1.0.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/scrawler.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/scrawler.png"
    background_color: "#5EAAA8"
    theme_color: "#5EAAA8"
  windows:
    generate: true
    image_path: "images/scrawler-desktop.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/scrawler-desktop.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
      - asset: res/Inter-Bold.ttf
      - asset: res/Inter-Light.ttf
      - asset: res/Inter-Regular.ttf

  assets:
    - images/bnotes.png
    - images/bnotes-transparent.png
    - images/scrawler.png
    - images/scrawler-desktop.png
    - images/google.png
    - images/undraw_playful_cat.svg
    - images/undraw_login.svg
    - images/welcome.svg
    - res/apikey
    - res/apiserver
    - res/languages.json