name: bnotes
description: Note taking application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.8.1
  intl: ^0.16.1
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.1
  uuid: ^2.2.2
  path_provider: ^1.6.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/bnotes.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/bnotes.png
    - images/google.png

  fonts:
    - family:  outline_material_icons
      fonts:
        - asset: res/outline_material_icons.ttf